document.write("<div id=\"logo\">");
document.write("<div id=\"logo_text\">");
document.write("<!-- class=\"logo_colour\", allows you to change the colour of the text -->");
document.write("<h1><a href=\"index.html\">Xin-Yu Ou<span class=\"logo_colour\">（欧新宇）</span></a></h1>");
document.write("<h2>教育的根是苦的，但是其果是甜的。</h2>");
document.write("</div>");
document.write("<div id=\"logo_badgeHUST\" class=\"logo_badge\">");
document.write("<a href=\"http://www.hust.edu.cn\" target=\"_blank\"><img src=\"Images/hust.png\" title=\"华中科技大学\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeYNU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.ynu.edu.cn\" target=\"_blank\"><img src=\"Images/ynu.png\" title=\"云南大学\" height=\"120\"></a>");
document.write("</div>");
document.write("<div id=\"logo_badgeYNOU\" class=\"logo_badge\">");
document.write("<a href=\"http://www.ynou.cn\" target=\"_blank\"><img src=\"Images/ynou.png\" title=\"云南开放大学\" height=\"120\"></a>");
document.write("</div>");
document.write("</div>");