document.write("<div class=\"sidebar\">");
document.write("<h3>Latest</h3>");
document.write("<p><a href=\"#\">Caffe + Ubuntu 14.04 + CUDA 6.5 新手安装配置指南</a> <i style=\"color:gray;\">[2014-07-23]</i></p>");
document.write("<p><a href=\"#\">Caffe配置指南 on Windows8.1 + CUDA6.5 + VS2013 </a> <i style=\"color:gray;\">[2014-07-19]</i></p>");
document.write("<p><a href=\"#\">Cuda-convnet配置指南 on Windows8.1 + CUDA6.5 + VS2013</a> <i style=\"color:gray;\">[2014-07-17]</i></p>");
document.write("<h3>Contact</h3>");
document.write("<ul>");
document.write("<li>E—Mail：shiorioxy@qq.com</li>");
document.write("<li style=\"text-indent:52px;\">ouxinyu@hust.edu.cn</li>");
document.write("<li>QQ/微信：14777591</li>");
document.write("</ul>");
document.write("</div>");